services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    command: flask run --host=0.0.0.0

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mygame
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
