services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mygame
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mygame
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./static/avatars:/app/static/avatars  # Сохраняет файлы после перезапуска
    ports:
      - "5432:5432"
    
    healthcheck:  # Добавляем healthcheck
      test: ["CMD-SHELL", "pg_isready -U user -d mygame"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  pgdata: